# Runs php-ast's tests and verifies that the package can be built.

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
    strategy:
      fail-fast: false
      matrix:
       include:
         # NOTE: If this is not quoted, the yaml parser will convert 7.0 to the number 7,
         # and the docker image `php:7` is the latest minor version of php 7.x (7.4).
         - PHP_VERSION: '7.0'
         - PHP_VERSION: '7.1'
         - PHP_VERSION: '7.2'
         - PHP_VERSION: '7.3'
         - PHP_VERSION: '7.4'
         - PHP_VERSION: '8.0'
         - PHP_VERSION: '8.1.0beta1'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build and test in docker
        run: bash ci/test_dockerized.sh ${{ matrix.PHP_VERSION }}
